name: Build and deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix-build nix -A doc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: result
      - uses: actions/deploy-pages@v4
