name: Build and deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix-build nix -A doc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: result
      - uses: actions/deploy-pages@v4

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix-build nix -A bins.static
          mkdir -p to-upload/nai-71c
          cp -r result/* to-upload/nai-71c/
      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-static"
          path: to-upload
